version: 0.0
os: linux

files:
  - source: ROOT.war
    destination: /home/ubuntu/deployments/
  - source: .env
    destination: /home/ubuntu/deployments/
  - source: scripts/
    destination: /home/ubuntu/deployments/scripts/

hooks:
  BeforeInstall:
    - location: /home/ubuntu/deployments/scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: /home/ubuntu/deployments/scripts/stop_server.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: /home/ubuntu/deployments/scripts/start_server.sh
      timeout: 300
      runas: root
